language: java
jdk:
  - openjdk8
before_install:
  - export TZ=Asia/Shanghai
  - pip install --user codecov
after_success:
  - codecov
branches:
  except:
    - appveyor

cache:
  directories:
  - $HOME/.m2
