<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.alibaba.fastjson2</groupId>
        <artifactId>fastjson2-parent</artifactId>
        <version>2.0.63</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>fastjson2</artifactId>
    <name>${project.artifactId}</name>
    <description>Fastjson is a JSON processor (JSON parser + JSON generator) written in Java</description>
    <packaging>jar</packaging>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <includes>
                        <include>com/alibaba/fastjson2/**/*.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <user.timezone>Asia/Shanghai</user.timezone>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
