package com.alibaba.fastjson3.util;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * ClassLoader for loading ASM-generated bytecode at runtime.
 */
@com.alibaba.fastjson3.annotation.JVMOnly
public class DynamicClassLoader
        extends ClassLoader {
    private static final Map<String, Class<?>> classMapping = new HashMap<>();
    private static final DynamicClassLoader instance = new DynamicClassLoader();

    private final Map<String, Class<?>> classes = new ConcurrentHashMap<>();

    static {
        Class<?>[] preloaded = {
                Object.class,
                java.lang.reflect.Type.class,
                java.lang.reflect.Field.class,
                java.lang.reflect.Method.class,

                // core3 types
                com.alibaba.fastjson3.JSONParser.class,
                com.alibaba.fastjson3.JSONGenerator.class,
                com.alibaba.fastjson3.ObjectReader.class,
                com.alibaba.fastjson3.ObjectWriter.class,
                com.alibaba.fastjson3.JSONObject.class,
                com.alibaba.fastjson3.JSONArray.class,
                com.alibaba.fastjson3.JSONException.class,
                com.alibaba.fastjson3.ObjectMapper.class,
                com.alibaba.fastjson3.reader.FieldReader.class,
                com.alibaba.fastjson3.reader.FieldNameMatcher.class,
                com.alibaba.fastjson3.writer.FieldWriter.class,
                com.alibaba.fastjson3.util.JDKUtils.class,

                // JDK types
                java.util.Collection.class,
                java.util.Set.class,
                java.util.List.class,
                java.util.ArrayList.class,
                java.util.LinkedList.class,
                java.util.Map.class,
                java.util.HashMap.class,
                java.util.LinkedHashMap.class,
                java.util.function.Supplier.class,

                Exception.class,
                Enum.class,
                Class.class,
                Boolean.class,
                Byte.class,
                Short.class,
                Integer.class,
                Long.class,
                Float.class,
                Double.class,
                String.class,
                java.math.BigInteger.class,
                java.math.BigDecimal.class,
        };
        for (Class<?> clazz : preloaded) {
            classMapping.put(clazz.getName(), clazz);
        }
    }

    public DynamicClassLoader() {
        this(getParentClassLoader());
    }

    public DynamicClassLoader(ClassLoader parent) {
        super(parent);
    }

    static ClassLoader getParentClassLoader() {
        ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
        if (contextClassLoader != null) {
            try {
                contextClassLoader.loadClass(DynamicClassLoader.class.getName());
                return contextClassLoader;
            } catch (ClassNotFoundException e) {
                // skip
            }
        }
        return DynamicClassLoader.class.getClassLoader();
    }

    @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        Class<?> mappingClass = classMapping.get(name);
        if (mappingClass != null) {
            return mappingClass;
        }

        Class<?> clazz = classes.get(name);
        if (clazz != null) {
            return clazz;
        }

        ClassNotFoundException error;
        try {
            return super.loadClass(name, resolve);
        } catch (ClassNotFoundException e) {
            error = e;
        }

        ClassLoader tcl = Thread.currentThread().getContextClassLoader();
        if (tcl != null && tcl != this) {
            try {
                return tcl.loadClass(name);
            } catch (ClassNotFoundException ignored) {
            }
        }

        throw error;
    }

    public Class<?> loadClass(String name, byte[] b, int off, int len) throws ClassFormatError {
        Class<?> clazz = defineClass(name, b, off, len);
        classes.put(name, clazz);
        return clazz;
    }

    public static DynamicClassLoader getInstance() {
        return instance;
    }
}
